a manage_my_process Bash scripts

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -8,14 +8,26 @@ if [[ "$#" == "1" ]]; then
         else
             ./manage_my_process &
             echo "$!" > /var/run/my_process.pid
-            echo "manage_my_process started"
+            if [[ -f /var/run/my_process.pid ]]; then
+                echo "manage_my_process started"
+            else
+                echo "Failed to start manage_my_process"
+            fi
         fi
 
     elif [[ "$1" == "stop" ]]; then
         if test -f "/var/run/my_process.pid"; then
-            kill "$(cat /var/run/my_process.pid)"
-            rm /var/run/my_process.pid
-            echo "manage_my_process stopped"
+            kill "$(cat /var/run/my_process.pid)" 2>/dev/null
+            if [[ $? -eq 0 ]]; then
+                rm /var/run/my_process.pid
+                if [[ ! -f /var/run/my_process.pid ]]; then
+                    echo "manage_my_process stopped"
+                else
+                    echo "Failed to delete /var/run/my_process.pid"
+                fi
+            else
+                echo "Failed to stop manage_my_process"
+            fi
         else
             echo "manage_my_process is not running"
         fi
@@ -23,7 +35,7 @@ if [[ "$#" == "1" ]]; then
     elif [[ "$1" == "restart" ]]; then
         # Stop program
         if test -f "/var/run/my_process.pid"; then
-            kill "$(cat /var/run/my_process.pid)"
+            kill "$(cat /var/run/my_process.pid)" 2>/dev/null
             rm /var/run/my_process.pid
         fi
 
