Write a manage_my_process Bash script

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -5,7 +5,7 @@ PID_FILE="/var/run/my_process.pid"
 
 if [[ "$#" == "1" ]]; then
     if [[ "$1" == "start" ]]; then
-        if test -f "$PID_FILE"; then
+        if [[ -f "$PID_FILE" ]]; then
             echo "manage_my_process is already running"
         else
             ./manage_my_process &  # Start the process in the background
@@ -14,19 +14,28 @@ if [[ "$#" == "1" ]]; then
         fi
 
     elif [[ "$1" == "stop" ]]; then
-        if test -f "$PID_FILE"; then
+        if [[ -f "$PID_FILE" ]]; then
             kill "$(cat "$PID_FILE")"  # Kill the process using the PID from the file
-            rm "$PID_FILE"  # Remove the PID file after stopping the process
-            echo "manage_my_process stopped"
+            if [ "$1" -eq 0 ]; then
+                rm "$PID_FILE"  # Remove the PID file after stopping the process
+                echo "manage_my_process stopped"
+            else
+                echo "Failed to stop manage_my_process"
+            fi
         else
             echo "No running instance of manage_my_process found."
         fi
 
     elif [[ "$1" == "restart" ]]; then
         # Stop the process if running
-        if test -f "$PID_FILE"; then
+        if [[ -f "$PID_FILE" ]]; then
             kill "$(cat "$PID_FILE")"  # Stop the process
-            rm "$PID_FILE"  # Remove the PID file
+            if [ "$1" -eq 0 ]; then
+                rm "$PID_FILE"  # Remove the PID file
+            else
+                echo "Failed to stop manage_my_process"
+                exit 1
+            fi
         fi
         # Start the process again
         ./manage_my_process &  # Start the process in the background
